- name: Install default provisioning packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - parted
    - curl

- name: Install default tool packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - zsh
    - moreutils
    - byobu
    - multitail
    - dnsutils
    - telnet
    - vim
    - tmux

- name: Install default compression packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - zip
    - unzip
    - bzip2
    - p7zip-full

- name: Install default development packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - git
    - sudo
    - cstream

- name: Install default filesystem packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - e2fsprogs
    - xfsprogs
    - btrfs-tools

- name: Install default other packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - incron
    - python-pip
