- name: Sysctl settings
  lineinfile:
    dest:   /etc/sysctl.conf
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
  with_items:
  # Send buffer sizes
   - { regexp: '^net.core.rmem_max',              line: 'net.core.rmem_max = 104857600' }
   - { regexp: '^net.core.rmem_default',          line: 'net.core.rmem_default = 8388608' }
   - { regexp: '^net.core.wmem_max',              line: 'net.core.wmem_max = 104857600' }
   - { regexp: '^net.core.wmem_default',          line: 'net.core.wmem_default = 8388608' }
   - { regexp: '^net.core.optmem_max',            line: 'net.core.optmem_max = 40960' }
   - { regexp: '^net.core.netdev_max_backlog',    line: 'net.core.netdev_max_backlog = 5000' }
   - { regexp: '^net.ipv4.tcp_rmem',              line: 'net.ipv4.tcp_rmem = 10240 524288 16777216' }
   - { regexp: '^net.ipv4.tcp_wmem',              line: 'net.ipv4.tcp_wmem = 10240 524288 16777216' }
   - { regexp: '^net.ipv4.tcp_wmem',              line: 'net.ipv4.tcp_wmem = 10240 524288 16777216' }
  # Connection tuning
   - { regexp: '^net.ipv4.tcp_timestamps',        line: 'net.ipv4.tcp_timestamps = 0' }
   - { regexp: '^net.ipv4.tcp_sack',              line: 'net.ipv4.tcp_sack = 1' }
   - { regexp: '^net.ipv4.tcp_fack',              line: 'net.ipv4.tcp_fack = 1' }
   - { regexp: '^net.ipv4.tcp_window_scaling',    line: 'net.ipv4.tcp_window_scaling = 1' }
   - { regexp: '^net.core.somaxconn',             line: 'net.core.somaxconn = 2048' }
   - { regexp: '^net.ipv4.tcp_max_syn_backlog',   line: 'net.ipv4.tcp_max_syn_backlog = 4096' }
   - { regexp: '^net.netfilter.nf_conntrack_max', line: 'net.netfilter.nf_conntrack_max = 100000' }
   - { regexp: '^net.nf_conntrack_max',           line: 'net.nf_conntrack_max = 100000' }
   - { regexp: '^net.ipv4.tcp_max_tw_buckets',    line: 'net.ipv4.tcp_max_tw_buckets = 180000' }
   - { regexp: '^net.ipv4.tcp_tw_recycle',        line: 'net.ipv4.tcp_tw_recycle = 0' }
   - { regexp: '^net.ipv4.tcp_tw_reuse',          line: 'net.ipv4.tcp_tw_reuse = 0' }
   - { regexp: '^net.ipv4.tcp_fin_timeout',       line: 'net.ipv4.tcp_fin_timeout = 10' }
  notify:
    - Apply sysctl settings
