- name: Deploy user files
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/user/files/profile/
    dest: /home/vagrant/
    delete: no

- name: Deploy additional aliases
  template:
    src:   roles/user/templates/vagrant_aliases.sh.j2
    dest:  /home/vagrant/.vagrant_aliases.sh
    owner: vagrant
    group: vagrant
    mode:  0774

- name: Fix rights
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: vagrant
    group: vagrant
    mode: '{{ item.mode }}'
  with_items:
   - { path: '/home/vagrant/',                     state : 'directory', mode: '0755' }
   - { path: '/home/vagrant/.ssh/',                state : 'directory', mode: '0700' }
   - { path: '/home/vagrant/.ssh/authorized_keys', state : 'file',      mode: '0600' }
   - { path: '/home/vagrant/.ssh/known_hosts',     state : 'file',      mode: '0644' }
   - { path: '/home/vagrant/.subversion/',         state : 'directory', mode: '0700' }
   - { path: '/home/vagrant/.subversion/config',   state : 'file',      mode: '0600' }
   - { path: '/home/vagrant/.my.cnf',              state : 'file',      mode: '0600' }
   - { path: '/home/vagrant/.gitconfig',           state : 'file',      mode: '0644' }

- name: Register aliases
  lineinfile:
    dest: '{{ item.file }}'
    regexp: 'source ~/.vagrant_aliases.sh'
    line:   'source ~/.vagrant_aliases.sh'
    state: present
  with_items:
   - { file: '/home/vagrant/.zshrc' }
   - { file: '/home/vagrant/.bashrc' }
