- name: Install rupa/z
  command: 'wget {{ item.remote }} -O {{ item.path }}'
  with_items:
   - { remote: 'https://raw.githubusercontent.com/rupa/z/master/z.sh', path: '/usr/local/bin/z.sh' }
  args:
    creates: '/usr/local/bin/z.sh'

- name: Fix rights
  file:
    path: '/usr/local/bin/z.sh'
    state: 'file'
    owner: vagrant
    group: vagrant
    mode: '0777'

- name: Register rupa/z
  lineinfile:
    dest: '{{ item.file }}'
    regexp: 'source /usr/local/bin/z.sh'
    line:   'source /usr/local/bin/z.sh'
    state: present
  with_items:
   - { file: '/home/vagrant/.zshrc' }
   - { file: '/home/vagrant/.bashrc' }

- name: Create rupa/z initial file
  file:
    path: '/home/vagrant/.z'
    state: 'touch'
    owner: vagrant
    group: vagrant
    mode: '0644'
