- name: Setup gitconfig
  lineinfile:
    dest:   '/home/vagrant/.gitconfig'
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
  with_items:
   - { regexp: '^[\s]*#?[\s]*name = REALNAME',  line : '    name = {{ PROFILE.realname }}' }
   - { regexp: '^[\s]*#?[\s]*email = USERNAME', line : '    email = {{ PROFILE.email }}' }
