- name: Install php
  apt:
    pkg:   '{{ item }}'
    state: latest
  with_items:
    # PHP
    - php5-cli
    - php5-curl
    - php5-mysqlnd
    - php5-xhprof
    - php5-memcache
    - php5-mcrypt
    - php5-gd
    - php5-sqlite
    - php5-xmlrpc
    - php5-xsl
    - php5-geoip
    - php5-ldap
    - php-pear