- name: Configure docker
  lineinfile:
    dest: '/etc/default/docker'
    regexp: '^#?DOCKER_OPTS\='
    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock {{ PROVISION.dockerOpts }}"'
    state: present
  notify:
    - Restart Docker

- name: Create /opt/docker/bin/ directory
  file:
    dest:  /opt/docker/bin/
    owner: vagrant
    group: vagrant
    mode:  0777
    state: directory

- name: Deploy docker bin files
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/docker/files/bin/
    dest: /opt/docker/bin/
    delete: no

- name: Install docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/{{ PACKAGES.dockerCompose }}/docker-compose-`uname -s`-`uname -m` > /opt/docker/bin/docker-compose.{{ PACKAGES.dockerCompose }}"
  args:
    creates: '/opt/docker/bin/docker-compose.{{ PACKAGES.dockerCompose }}'

- name: Fix rights
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: vagrant
    group: vagrant
    mode: '{{ item.mode }}'
  with_items:
   - { path: '/opt/docker/bin/docker-compose.{{ PACKAGES.dockerCompose }}', state : 'file', mode: '0777' }
   - { path: '/opt/docker/bin/compose-wrapper.sh', state : 'file', mode: '0777' }

- name: Add symlinks
  file:
    src:  '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: 'link'
    owner: vagrant
    group: vagrant
    mode: '0777'
    force: yes
  with_items:
   - { src: '/opt/docker/bin/docker-compose.{{ PACKAGES.dockerCompose }}', dest: '/usr/local/bin/docker-compose' }
   - { src: '/opt/docker/bin/compose-wrapper.sh',   dest: '/usr/local/bin/dcc' }

#############################
# Apparmor profile
#############################

- name: Fix AppArmor profile
  lineinfile:
    dest:        '/etc/apparmor.d/docker'
    insertafter: '[\s]*capability'
    line:        '  ptrace peer=docker-default,'
    state:       present
  notify:
    - Reload AppArmor
