- name: Configure docker
  lineinfile:
    dest: '/etc/default/docker'
    regexp: '^#?DOCKER_OPTS\='
    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --insecure-registry {{ dockerRegistry }}"'
    state: present
  when: dockerRegistry is defined

- name: Configure docker
  lineinfile:
    dest: '/etc/default/docker'
    regexp: '^#?DOCKER_OPTS\='
    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"'
    state: present
  when: dockerRegistry is not defined

- name: Restart docker
  command: 'service docker restart'

- name: Create /opt/docker/bin/ directory
  file:
    dest:  /opt/docker/bin/
    owner: vagrant
    group: vagrant
    mode:  0777
    state: directory

- name: Deploy docker bin files
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/docker/files/bin/
    dest: /opt/docker/bin/
    delete: no

- name: Install docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /opt/docker/bin/docker-compose.1.2.0"
  args:
    creates: '/opt/docker/bin/docker-compose.1.2.0'

- name: Fix rights
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: vagrant
    group: vagrant
    mode: '{{ item.mode }}'
  with_items:
   - { path: '/opt/docker/bin/docker-compose.1.2.0', state : 'file', mode: '777' }
   - { path: '/opt/docker/bin/compose-wrapper.sh', state : 'file', mode: '777' }

- name: Add symlinks
  file:
    src:  '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: 'link'
    owner: vagrant
    group: vagrant
    mode: '777'
    force: yes
  with_items:
   - { src: '/opt/docker/bin/docker-compose.1.2.0', dest: '/usr/local/bin/docker-compose' }
   - { src: '/opt/docker/bin/compose-wrapper.sh',   dest: '/usr/local/bin/dcc' }

