---

- name: Cleanup old orphaned docker images
  shell: 'docker system prune -f'
  when: DOCKER.cleanup.system is defined and DOCKER.cleanup.system
  ignore_errors: yes

- name: Cleanup old temp builds
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /var/lib/docker/tmp/*
  when: DOCKER.cleanup.tmp is defined and DOCKER.cleanup.tmp
  ignore_errors: yes
