- name: Deploy postfix configuration
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/mail/files/postfix/
    dest: /etc/postfix/
    delete: no

- name: Postfix configuration
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
  with_items:
    - { regexp: '^smtpd_banner',             line: 'smtpd_banner = $myhostname ESMTP DEVELOPMENT-VM' }
    - { regexp: '^inet_interfaces',          line: 'inet_interfaces = 127.0.0.1,{{ ansible_eth1.ipv4.address }}' }
    - { regexp: '^header_checks',            line: 'header_checks = regexp:/etc/postfix/additional_headers' }
    - { regexp: '^recipient_canonical_maps', line: 'recipient_canonical_maps = regexp:/etc/postfix/recipient_canonical_maps' }
    - { regexp: '^home_mailbox',             line: 'home_mailbox = .mail/' }
    - { regexp: '^mynetworks',               line: 'mynetworks = 127.0.0.0/8 168.100.189.0/28 [::1]/128 [fe80::]/10 [2001:240:587::]/64 172.16.0.0/12 {{ ansible_eth1.ipv4.network }}/24  [{{ ansible_eth1.ipv6.address }}]/{{ ansible_eth1.ipv6.prefix }}' }

- name: Enable additional_headers
  lineinfile: dest=/etc/postfix/main.cf regexp='header_checks' line='header_checks = regexp:/etc/postfix/additional_headers'

- name: Init postfix
  raw: '{{ item }}'
  with_items:
    - postmap /etc/postfix/recipient_canonical_maps
    - postmap /etc/postfix/additional_headers
    - service postfix restart
